apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
