apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    platform.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://kyverno.github.io/kyverno/"
    chart: kyverno
    targetRevision: "3.7.1"
    helm:
      values: |
        replicaCount: 1
        resources:
          limits:
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
