apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-alert-rules
  namespace: argocd
  labels:
    platform.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/kendricklawton/hetzner-k8s-platform.git
    targetRevision: HEAD
    path: infra/manifests/alerts
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
