apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: Application
      name: ingress-nginx
    patch: |-
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: "controller.config.use-proxy-protocol"
          value: "true"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: "controller.service.annotations.load-balancer\\.hetzner\\.cloud/use-private-ip"
          value: "true"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: "controller.service.annotations.load-balancer\\.hetzner\\.cloud/uses-proxyprotocol"
          value: "true"
      - op: add
        path: /spec/source/helm/parameters/-
        value:
          name: "controller.service.annotations.load-balancer\\.hetzner\\.cloud/name"
          value: "dev-ash-lb-ingress"
